#!/usr/bin/env perl

# quvi.git/.git/hooks/pre-commit 

use warnings;
use strict;

my $INDENT="indent -linux  --no-tabs -i2";

foreach (qw('*.c' '*.h')) {
  my $c = qq/find . -name $_ -exec $INDENT "{}" \\;/;
#  print "$c\n";
  qx/$c/;
  exit $?  unless $? == 0;
}

#qx/find . -name '*~' -exec rm {} \\;/;

exit 0
